<?php

// generated by updateConfig.php on 24/02/2017 10:43(Europe/Paris time)

require_once realpath(dirname(dirname(__FILE__))).'/vendor/autoload.php';
use Monolog\Logger;
if (! isset($_SESSION)) session_start();

// global setting
$_SESSION['ENVIRONMENT'] = 'HOMO';
$_SESSION['MERCHANT_ID'] = '37334959742602';
$_SESSION['MERCHANT_NAME'] = "DEMO MODULES";
$_SESSION['ACCESS_KEY'] = 'HadaKnVOG8tnhbLft3yD';
$_SESSION['ACCESS_KEY_REF'] = '';
$_SESSION['WS_VERSION'] = '16';
$_SESSION['PROXY_HOST'] = '127.0.0.1';
$_SESSION['PROXY_PORT'] = '5000';
$_SESSION['PROXY_LOGIN'] = '';
$_SESSION['PROXY_PASSWORD'] = '';

// demo settings
$_SESSION['KIT_ROOT'] = 'http://127.0.0.1/payline-php-samples/';
$_SESSION['LOG_PATH'] = 'D:\\wamp\\www\\payline-php-samples\\logs\\';
$_SESSION['LOG_LEVEL'] = Logger::DEBUG;

// payment setting
$_SESSION['PAYMENT_CURRENCY'] = '978';
$_SESSION['ORDER_CURRENCY'] = '978';
$_SESSION['LANGUAGE_CODE'] = 'en';
$_SESSION['PAYMENT_ACTION'] = '101';
$_SESSION['PAYMENT_MODE'] = 'CPT';
$_SESSION['CUSTOM_PAYMENT_TEMPLATE_URL'] = '';
$_SESSION['CUSTOM_PAYMENT_PAGE_CODE'] = '';
$_SESSION['CONTRACT_NUMBER'] = '1234567';
$_SESSION['CONTRACT_NUMBER_LIST'] = '1234567';
$_SESSION['SECOND_CONTRACT_NUMBER_LIST'] = '';
$_SESSION['WALLET_CONTRACT_NUMBER_LIST'] = '';
$_SESSION['RETURN_URL'] = 'http://127.0.0.1/payline-php-samples/examples/demos/web.php?e=getWebPaymentDetails';
$_SESSION['NOTIFICATION_URL'] = '';
$_SESSION['CANCEL_URL'] = 'http://127.0.0.1/payline-php-samples/examples/demos/web.php?e=getWebPaymentDetails';

// buyer info
$_SESSION['buyerLegalStatus'] = '1';
$_SESSION['buyerTitle'] = 'Mr';
$_SESSION['buyerLastName'] = "SUAREZ";
$_SESSION['buyerFirstName'] = "Fabien";
$_SESSION['buyerEmail'] = 'fabien.suarez@payline.com';
$_SESSION['billingAddressTitle'] = "Mr";
$_SESSION['billingAddressFirstName'] = "Fabien";
$_SESSION['billingAddressLastName'] = "SUAREZ";
$_SESSION['billingAddressName'] = "La Défense";
$_SESSION['billingAddressStreet1'] = "5, Place de la Pyramide";
$_SESSION['billingAddressStreet2'] = "Tour Ariane";
$_SESSION['billingAddressCity'] = "Courbevoie";
$_SESSION['billingAddressZipCode'] = '92088';
$_SESSION['billingAddressCountry'] = "France";
$_SESSION['billingAddressCounty'] = "";
$_SESSION['billingAddressState'] = "";
$_SESSION['billingAddressPhoneType'] = '';
$_SESSION['billingAddressPhone'] = '0141456767';
$_SESSION['shippingAddressTitle'] = 'Mr';
$_SESSION['shippingAddressFirstName'] = "Fabien";
$_SESSION['shippingAddressLastName'] = "SUAREZ";
$_SESSION['shippingAddressName'] = "Ledoux";
$_SESSION['shippingAddressStreet1'] = "260, rue Claude Nicolas Ledoux";
$_SESSION['shippingAddressStreet2'] = "Pôle d'Activités d'Aix-en-Provence";
$_SESSION['shippingAddressCity'] = "Aix-en-Provence Cedex 3";
$_SESSION['shippingAddressZipCode'] = '13593';
$_SESSION['shippingAddressCountry'] = "France";
$_SESSION['shippingAddressCounty'] = "";
$_SESSION['shippingAddressState'] = "";
$_SESSION['shippingAddressPhoneType'] = '';
$_SESSION['shippingAddressPhone'] = '0442251468';
$_SESSION['buyerAccountCreateDate'] = '';
$_SESSION['buyerAverageAmount'] = '';
$_SESSION['buyerOrderCount'] = '';
$_SESSION['buyerWalletId'] = "";
$_SESSION['buyerWalletDisplayed'] = '';
$_SESSION['buyerWalletSecured'] = '';
$_SESSION['buyerWalletCardInd'] = '';
$_SESSION['buyerIp'] = '';
$_SESSION['mobilePhone'] = '0689793619';
$_SESSION['customerId'] = "";
$_SESSION['legalDocument'] = '';
$_SESSION['birthDate'] = '';
$_SESSION['fingerprintID'] = "";
$_SESSION['deviceFingerprint'] = "";
$_SESSION['isIncognito'] = '';
$_SESSION['isBot'] = '';
$_SESSION['isBehindProxy'] = '';
$_SESSION['isFromTor'] = '';
$_SESSION['isEmulator'] = '';
$_SESSION['isRooted'] = '';
$_SESSION['hasTimezoneMismatch'] = '';

// private data
$_SESSION['pvdKey1'] = '';
$_SESSION['pvdValue1'] = '';
$_SESSION['pvdKey2'] = '';
$_SESSION['pvdValue2'] = '';
$_SESSION['pvdKey3'] = '';
$_SESSION['pvdValue3'] = '';
$_SESSION['pvdKey4'] = '';
$_SESSION['pvdValue4'] = '';
$_SESSION['pvdKey5'] = '';
$_SESSION['pvdValue5'] = '';
$_SESSION['pvdKey6'] = '';
$_SESSION['pvdValue6'] = '';
$_SESSION['pvdKey7'] = '';
$_SESSION['pvdValue7'] = '';
$_SESSION['pvdKey8'] = '';
$_SESSION['pvdValue8'] = '';
?> 
