<?php
$update_config_status = 0;
session_start();

$configFile = '../../lib/CONFIG.php';
$nextLine = "\n";
if(is_writable($configFile)){
	$handle = fopen($configFile, 'w');
	fwrite($handle, '<?php'.$nextLine.$nextLine);
	$timezone = "Europe/Paris";
	date_default_timezone_set($timezone);
	fwrite($handle, '// generated by updateConfig.php on '.date('d/m/Y H:i').'('.$timezone.' time)'.$nextLine.$nextLine);
	fwrite($handle, 'require_once realpath(dirname(dirname(__FILE__))).\'/vendor/autoload.php\';'.$nextLine);
	fwrite($handle, 'use Monolog\Logger;'.$nextLine);
	fwrite($handle, 'if (! isset($_SESSION)) session_start();'.$nextLine.$nextLine);
	
	fwrite($handle, '// global setting'.$nextLine);
	fwrite($handle, '$_SESSION[\'ENVIRONMENT\'] = \''.$_POST['ENVIRONMENT'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'MERCHANT_ID\'] = \''.trim($_POST['MERCHANT_ID']).'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'MERCHANT_NAME\'] = "'.$_POST['MERCHANT_NAME'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'ACCESS_KEY\'] = \''.trim($_POST['ACCESS_KEY']).'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'ACCESS_KEY_REF\'] = \''.trim($_POST['ACCESS_KEY_REF']).'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'WS_VERSION\'] = \''.$_POST['WS_VERSION'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PROXY_HOST\'] = \''.trim($_POST['PROXY_HOST']).'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PROXY_PORT\'] = \''.trim($_POST['PROXY_PORT']).'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PROXY_LOGIN\'] = \''.trim($_POST['PROXY_LOGIN']).'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PROXY_PASSWORD\'] = \''.trim($_POST['PROXY_PASSWORD']).'\';'.$nextLine);
	fwrite($handle, $nextLine.'// demo settings'.$nextLine);
	$parsedUrl = parse_url($_SERVER['HTTP_REFERER']);
	$parsedPath = explode('examples', $parsedUrl['path']);
	$kitRoot = $parsedUrl['scheme'].'://'.$parsedUrl['host'].$parsedPath[0];
	fwrite($handle, '$_SESSION[\'KIT_ROOT\'] = \''.$kitRoot.'\';'.$nextLine);
	$filesRoot = realpath(dirname(dirname(dirname(__FILE__)))) . DIRECTORY_SEPARATOR;
	$cssPath = $filesRoot . 'examples' . DIRECTORY_SEPARATOR . 'demos' . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR;
	$cssPath = str_replace('\\', '\\\\', $cssPath);
	$jsPath = $filesRoot . 'examples' . DIRECTORY_SEPARATOR . 'demos' . DIRECTORY_SEPARATOR . 'scripts' . DIRECTORY_SEPARATOR;
	$jsPath = str_replace('\\', '\\\\', $jsPath);
	$logPath = $filesRoot . 'logs' . DIRECTORY_SEPARATOR;
	$logPath = str_replace('\\', '\\\\', $logPath);
	fwrite($handle, '$_SESSION[\'JS_PATH\'] = \''.$jsPath.'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'CSS_PATH\'] = \''.$cssPath.'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'LOG_PATH\'] = \''.$logPath.'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'LOG_LEVEL\'] = '.$_POST['LOG_LEVEL'].';'.$nextLine);
	
	fwrite($handle, $nextLine.'// payment setting'.$nextLine);
	fwrite($handle, '$_SESSION[\'PAYMENT_AMOUNT\'] = \''.$_POST['PAYMENT_AMOUNT'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PAYMENT_CURRENCY\'] = \''.$_POST['PAYMENT_CURRENCY'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'LANGUAGE_CODE\'] = \''.$_POST['LANGUAGE_CODE'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PAYMENT_ACTION\'] = \''.$_POST['PAYMENT_ACTION'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'PAYMENT_MODE\'] = \''.$_POST['PAYMENT_MODE'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'CUSTOM_PAYMENT_TEMPLATE_URL\'] = \''.$_POST['CUSTOM_PAYMENT_TEMPLATE_URL'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'CUSTOM_PAYMENT_PAGE_CODE\'] = \''.$_POST['CUSTOM_PAYMENT_PAGE_CODE'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'CONTRACT_NUMBER\'] = \''.$_POST['CONTRACT_NUMBER'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'CONTRACT_NUMBER_LIST\'] = \''.$_POST['CONTRACT_NUMBER_LIST'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'SECOND_CONTRACT_NUMBER_LIST\'] = \''.$_POST['SECOND_CONTRACT_NUMBER_LIST'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'WALLET_CONTRACT_NUMBER_LIST\'] = \''.$_POST['WALLET_CONTRACT_NUMBER_LIST'].'\';'.$nextLine);
	if($_POST['returnURL'] == ''){
	    fwrite($handle, '$_SESSION[\'RETURN_URL\'] = \''.$kitRoot.'examples/demos/web.php?e=getWebPaymentDetails'.'\';'.$nextLine);
	}else{
	    fwrite($handle, '$_SESSION[\'RETURN_URL\'] = \''.$_POST['returnURL'].'\';'.$nextLine);
	}
	fwrite($handle, '$_SESSION[\'NOTIFICATION_URL\'] = \''.$_POST['notificationURL'].'\';'.$nextLine);
	if($_POST['cancelURL'] == ''){
	    fwrite($handle, '$_SESSION[\'CANCEL_URL\'] = \''.$kitRoot.'examples/demos/web.php?e=getWebPaymentDetails'.'\';'.$nextLine);
	}else{
	    fwrite($handle, '$_SESSION[\'CANCEL_URL\'] = \''.$_POST['cancelURL'].'\';'.$nextLine);
	}
	
	if($_POST['walletReturnURL'] == ''){
	    fwrite($handle, '$_SESSION[\'WLT_RETURN_URL\'] = \''.$kitRoot.'examples/demos/wallet.php?e=getWebWallet'.'\';'.$nextLine);
	}else{
	    fwrite($handle, '$_SESSION[\'WLT_RETURN_URL\'] = \''.$_POST['walletReturnURL'].'\';'.$nextLine);
	}
	fwrite($handle, '$_SESSION[\'WLT_NOTIFICATION_URL\'] = \''.$_POST['walletNotificationURL'].'\';'.$nextLine);
	if($_POST['walletCancelURL'] == ''){
	    fwrite($handle, '$_SESSION[\'WLT_CANCEL_URL\'] = \''.$kitRoot.'examples/demos/wallet.php?e=getWebWallet'.'\';'.$nextLine);
	}else{
	    fwrite($handle, '$_SESSION[\'WLT_CANCEL_URL\'] = \''.$_POST['walletCancelURL'].'\';'.$nextLine);
	}
	
	$noCssFlag = true;
	if(isset($_FILES['inCss']) && $_FILES['inCss']['name'] != ''){
	    $noCssFlag = false;
	    if($_FILES['inCss']['error'] > 0){ // transfert KO
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = null;'.$nextLine);
	        $update_config_status = 6;
	    }else{
	        $cssName = $_POST['ENVIRONMENT'].'_'.trim($_POST['MERCHANT_ID']).'_widget_'.date('YmdHis').'.css';
	        $destCss = $cssPath . $cssName;
	        if(move_uploaded_file($_FILES['inCss']['tmp_name'], $destCss)){
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = \''.$cssName.'\';'.$nextLine);
	        }else{ // transfert KO
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = null;'.$nextLine);
	            $update_config_status = 6;
	        }
	    }
	}
	if(isset($_POST['inCss']) && $_POST['inCss'] != ''){
	    $noCssFlag = false;
	    $cssFileName = $_SESSION['CSS_PATH'] . DIRECTORY_SEPARATOR . $_POST['inCss'];
	    if(!file_exists($cssFileName)){ 
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = null;'.$nextLine);
	    }else{
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = \''.$_POST['inCss'].'\';'.$nextLine);
	    }
	}
	if(isset($_POST['deleteFile']) && $_POST['deleteFile'] == "CSS"){
	    $noCssFlag = false;
	    $cssFileName = $_SESSION['CSS_PATH'] . DIRECTORY_SEPARATOR . $_SESSION['CUSTOM_WIDGET_CSS'];
	    if(!file_exists($cssFileName)){
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = null;'.$nextLine);
	    }else{
	        if(!unlink($cssFileName)){
	            $update_config_status = 4;
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = \''.$_SESSION['CUSTOM_WIDGET_CSS'].'\';'.$nextLine);
	        }else{
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = null;'.$nextLine);
	        }
	    }
    }
    if($noCssFlag){
        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_CSS\'] = null;'.$nextLine);
    }	    	   
	
	$noJsFlag = true;
	if(isset($_FILES['inJs']) && $_FILES['inJs']['name'] != ''){
	    $noJsFlag = false;
	    if($_FILES['inJs']['error'] > 0){ // transfert KO
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = null;'.$nextLine);
	        $update_config_status = 6;
	    }else{
	        $jsName = $_POST['ENVIRONMENT'].'_'.trim($_POST['MERCHANT_ID']).'_widget_'.date('YmdHis').'.js';
	        $destJs = $jsPath . $jsName;
	        if(move_uploaded_file($_FILES['inJs']['tmp_name'], $destJs)){
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = \''.$jsName.'\';'.$nextLine);
	        }else{ // transfert KO
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = null;'.$nextLine);
	            $update_config_status = 6;
	        }
	    }
	}
	if(isset($_POST['inJs'])){
	    $noJsFlag = false;
	    $jsFileName = $_SESSION['JS_PATH'] . DIRECTORY_SEPARATOR . $_POST['inJs'];
	    if(!file_exists($jsFileName)){
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = null;'.$nextLine);
	    }else{
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = \''.$_POST['inJs'].'\';'.$nextLine);
	    }
	}
	if(isset($_POST['deleteFile']) && $_POST['deleteFile'] == "JS"){
	    $noJsFlag = false;
	    $jsFileName = $_SESSION['JS_PATH'] . DIRECTORY_SEPARATOR . $_SESSION['CUSTOM_WIDGET_JS'];
	    if(!file_exists($jsFileName)){
	        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = null;'.$nextLine);
	    }else{
	        if(!unlink($jsFileName)){
	            $update_config_status = 4;
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = \''.$_SESSION['CUSTOM_WIDGET_JS'].'\';'.$nextLine);
	        }else{
	            fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = null;'.$nextLine);
	        }
	    }
    }
    if($noJsFlag){
        fwrite($handle, '$_SESSION[\'CUSTOM_WIDGET_JS\'] = null;'.$nextLine);
    }
    
	fwrite($handle, $nextLine.'// buyer info'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerLegalStatus\'] = \''.$_POST['buyerLegalStatus'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerTitle\'] = \''.$_POST['buyerTitle'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerLastName\'] = "'.$_POST['buyerLastName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerFirstName\'] = "'.$_POST['buyerFirstName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerEmail\'] = \''.$_POST['buyerEmail'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressTitle\'] = "'.$_POST['billingAddressTitle'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressFirstName\'] = "'.$_POST['billingAddressFirstName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressLastName\'] = "'.$_POST['billingAddressLastName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressName\'] = "'.$_POST['billingAddressName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressStreet1\'] = "'.$_POST['billingAddressStreet1'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressStreet2\'] = "'.$_POST['billingAddressStreet2'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressCity\'] = "'.$_POST['billingAddressCity'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressZipCode\'] = \''.$_POST['billingAddressZipCode'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressCountry\'] = "'.$_POST['billingAddressCountry'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressCounty\'] = "'.$_POST['billingAddressCounty'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressState\'] = "'.$_POST['billingAddressState'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressPhoneType\'] = \''.$_POST['billingAddressPhoneType'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'billingAddressPhone\'] = \''.$_POST['billingAddressPhone'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressTitle\'] = \''.$_POST['shippingAddressTitle'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressFirstName\'] = "'.$_POST['shippingAddressFirstName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressLastName\'] = "'.$_POST['shippingAddressLastName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressName\'] = "'.$_POST['shippingAddressName'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressStreet1\'] = "'.$_POST['shippingAddressStreet1'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressStreet2\'] = "'.$_POST['shippingAddressStreet2'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressCity\'] = "'.$_POST['shippingAddressCity'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressZipCode\'] = \''.$_POST['shippingAddressZipCode'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressCountry\'] = "'.$_POST['shippingAddressCountry'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressCounty\'] = "'.$_POST['shippingAddressCounty'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressState\'] = "'.$_POST['shippingAddressState'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressPhoneType\'] = \''.$_POST['shippingAddressPhoneType'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'shippingAddressPhone\'] = \''.$_POST['shippingAddressPhone'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerAccountCreateDate\'] = \''.$_POST['buyerAccountCreateDate'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerAverageAmount\'] = \''.$_POST['buyerAverageAmount'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerOrderCount\'] = \''.$_POST['buyerOrderCount'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerWalletId\'] = "'.$_POST['buyerWalletId'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerWalletDisplayed\'] = \''.$_POST['buyerWalletDisplayed'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerWalletSecured\'] = \''.$_POST['buyerWalletSecured'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerWalletCardInd\'] = \''.$_POST['buyerWalletCardInd'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'buyerIp\'] = \''.$_POST['buyerIp'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'mobilePhone\'] = \''.$_POST['mobilePhone'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'customerId\'] = "'.$_POST['customerId'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'legalDocument\'] = \''.$_POST['legalDocument'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'birthDate\'] = \''.$_POST['birthDate'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'fingerprintID\'] = "'.$_POST['fingerprintID'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'deviceFingerprint\'] = "'.$_POST['deviceFingerprint'].'";'.$nextLine);
	fwrite($handle, '$_SESSION[\'isIncognito\'] = \''.$_POST['isIncognito'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'isBot\'] = \''.$_POST['isBot'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'isBehindProxy\'] = \''.$_POST['isBehindProxy'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'isFromTor\'] = \''.$_POST['isFromTor'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'isEmulator\'] = \''.$_POST['isEmulator'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'isRooted\'] = \''.$_POST['isRooted'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'hasTimezoneMismatch\'] = \''.$_POST['hasTimezoneMismatch'].'\';'.$nextLine);
	fwrite($handle, $nextLine.'// private data'.$nextLine);
	for ($i=1;$i<9;$i++) {
	    fwrite($handle, '$_SESSION[\'pvdKey'.$i.'\'] = \''.$_POST['privateDataKey0'.$i].'\';'.$nextLine);
	    fwrite($handle, '$_SESSION[\'pvdValue'.$i.'\'] = \''.$_POST['privateDataValue0'.$i].'\';'.$nextLine);
	}
	
	fwrite($handle, $nextLine.'// order info'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderOrigin\'] = \''.$_POST['orderOrigin'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderCountry\'] = \''.$_POST['orderCountry'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderTaxes\'] = \''.$_POST['orderTaxes'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderCurrency\'] = \''.$_POST['orderCurrency'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderAmount\'] = \''.$_POST['orderAmount'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'deliveryTime\'] = \''.$_POST['deliveryTime'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'deliveryMode\'] = \''.$_POST['deliveryMode'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailRef1\'] = \''.$_POST['orderDetailRef1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailPrice1\'] = \''.$_POST['orderDetailPrice1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailQuantity1\'] = \''.$_POST['orderDetailQuantity1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailComment1\'] = \''.$_POST['orderDetailComment1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailCategory1\'] = \''.$_POST['orderDetailCategory1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailSubcategory1_1\'] = \''.$_POST['orderDetailSubcategory1_1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailSubcategory2_1\'] = \''.$_POST['orderDetailSubcategory2_1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailBrand1\'] = \''.$_POST['orderDetailBrand1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailAdditionalData1\'] = \''.$_POST['orderDetailAdditionalData1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailTaxRate1\'] = \''.$_POST['orderDetailTaxRate1'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailRef2\'] = \''.$_POST['orderDetailRef2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailPrice2\'] = \''.$_POST['orderDetailPrice2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailQuantity2\'] = \''.$_POST['orderDetailQuantity2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailComment2\'] = \''.$_POST['orderDetailComment2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailCategory2\'] = \''.$_POST['orderDetailCategory2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailSubcategory1_2\'] = \''.$_POST['orderDetailSubcategory1_2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailSubcategory2_2\'] = \''.$_POST['orderDetailSubcategory2_2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailBrand2\'] = \''.$_POST['orderDetailBrand2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailAdditionalData2\'] = \''.$_POST['orderDetailAdditionalData2'].'\';'.$nextLine);
	fwrite($handle, '$_SESSION[\'orderDetailTaxRate2\'] = \''.$_POST['orderDetailTaxRate2'].'\';'.$nextLine);
	
	fwrite($handle, "?> \n");
	fclose($handle);
}else{
	$update_config_status = 3;
}
$_SESSION = array();
header("Location: ../demos/index.php?e=configuration&res_upd=$update_config_status");
?>